package DedomartC::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'DedomartC::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:dombeemain',
        user => 'xxxxxxxxxx',
        password => 'xxxxxx',
        AutoCommit => q{1},
    }
);

=head1 NAME

DedomartC::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<DedomartC>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<DedomartC::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

user

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
